block-message: '&6PebbleAntiVPN%nl%&cProxy/VPN Detected.'
console-filter: true
bypass-permission: pav.bypass
users-per-ip:
  enabled: false
  limit: 3
  kick-message: '&6PebbleAntiVPN%nl%&cYou have exceeded the max number of connections per IP.'
blocked-countries:
  enabled: false
  kick-message: '&6PebbleAntiVPN%nl%&cYour country is blocked from this server.'
  countries:
    - Template
alerts:
  console:
    enabled: true
    message: '&e%player% &bwas discovered to be using a VPN/Proxy, IP: &e%ip%'
  players:
    enabled: true
    permission: pav.alert
    message: '&e%player% &bwas discovered to be using a VPN/Proxy, IP: &e%ip%'